# Docker Compose para produção
version: '3.8'

services:
  extension-build:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: production
    container_name: security-web-production
    volumes:
      - ./dist:/app/dist
    environment:
      - NODE_ENV=production
    restart: "no"

volumes:
  production_dist:
